pipeline {
    agent any 
    tools {
        maven "M3"
    }
    environment {
        registryCredential = 'dockerhub_id'
    }
    stages {
        stage('Compile and Clean') { 
            steps {
                // Run Maven on a Unix agent.
              
                sh "mvn -f catalogmanagement/ clean compile"
            }
        }
        stage('deploy') { 
            
            steps {
                sh "mvn -f catalogmanagement/ package"
                sh "ls /var/lib/jenkins/workspace/catalogmanagementpipeline/catalogmanagement/target/"
                sh "cp /var/lib/jenkins/workspace/catalogmanagementpipeline/catalogmanagement/target/catalog-management-docker.jar /home/ec2-user/catalog-management-docker.jar"
            }
        }
        stage('Build Docker image'){
          
            steps {
                echo "Hello Java Express"
                sh 'ls'
                sh 'docker build -f catalogmanagement/Dockerfile -t ravinderdabgotra/catalogmanagement:${BUILD_NUMBER} .'
            }
        }
        stage('Docker Login'){
            
            steps{
                script {
                    docker.withRegistry( '', registryCredential ) {
                        dockerImage.push()
                    }
                }
            }           
        }
        stage('Docker Push'){
            steps {
                sh 'docker push ravinderkumard/catalogmanagement:${BUILD_NUMBER}'
            }
        }
        stage('Docker deploy'){
            steps {
               
                sh 'docker run -itd -p  8081:8080 ravinderkumard/catalogmanagement:${BUILD_NUMBER}'
            }
        }
        stage('Archving') { 
            steps {
                 archiveArtifacts '**/target/*.jar'
            }
        }
    }
}
