pipeline {
    agent any 
    tools {
        maven "M3"
    }
    environment {
        registryCredential = 'dockerhub'
        DOCKER_REGISTRY_URL = 'http://hub.docker.com'
        DOCKER_REGISTRY_CREDENTIALS_ID = 'dockerhub'
        DOCKER_REPO = 'ravinderdabgotra'
        IMAGE_NAME = 'catalogmanagement'
        IMAGE_TAG = '1.0'
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
        AWS_CREDENTIALS = credentials('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
        AWS_DEFAULT_REGION = 'us-east-1'
        DOCKER_IMAGE = 'catalogmanagement'
        ECS_CLUSTER = 'arn:aws:ecs:us-east-1:872115738621:cluster/MyeComCluster'
        ECS_SERVICE = 'arn:aws:ecs:us-east-1:872115738621:service/MyeComCluster/catalogmanagement'
    }
    stages {
        stage('Compile and Clean') { 
            steps {
                // Run Maven on a Unix agent.
              
                sh "mvn -f catalogmanagement/ clean compile"
            }
        }
        stage('deploy') { 
            
            steps {
                sh "mvn -f catalogmanagement/ package"
                sh "ls /var/lib/jenkins/workspace/catalogmanagementpipeline/catalogmanagement/target/"
            }
        }
        stage('Build Docker image'){
          
            steps {

                sh 'docker build -f catalogmanagement/Dockerfile -t ravinderdabgotra/catalogmanagement:${BUILD_NUMBER} .'
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR -p $DOCKERHUB_CREDENTIALS_PSW'
            }
        }
        stage('Docker Push'){
            steps {
                sh 'docker push ravinderdabgotra/catalogmanagement:${BUILD_NUMBER}'
            }
        }
        stage('Docker deploy'){
            steps {
               sh "cp catalogmanagement/task_defintion.json ."
                // sh 'docker run -itd -p  18080:18080 ravinderdabgotra/catalogmanagement:${BUILD_NUMBER}'
            }
        }
        
        stage('Deploy to ECS') {
            steps {
                script {
                    // Authenticate with AWS
                        
                        sh 'aws configure set aws_access_key_id $AWS_CREDENTIALS_USR'
                        sh 'aws configure set aws_secret_access_key $AWS_CREDENTIALS_PSW'
                        sh 'aws configure set default.region $AWS_DEFAULT_REGION'
                        
                        // Register a new task definition
                        sh "aws ecs register-task-definition --cli-input-json file://catalogmanagement/task_defintion.json --region $AWS_DEFAULT_REGION"
                        sh "REVISION=`aws ecs describe-task-definition --task-definition ${FAMILY} --region ${REGION} | jq .taskDefinition.revision`"
                        // Update ECS service
                        sh "aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --task-definition ${FAMILY}:${REVISION} --force-new-deployment --region $AWS_DEFAULT_REGION"
                    
                }
            }
        }
        stage('Archving') { 
            steps {
                 archiveArtifacts '**/target/*.jar'
            }
        }
    }
}
